            - name: Python Poetry Action
  # You may pin to the exact commit or the version.
  # uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439
  uses: abatilo/actions-poetry@v3.0.0
  with:
    # The version of poetry to install
    poetry-version: # optional, default is latest
    # The whitespace/newline-separated list of poetry plugins to install.
    poetry-plugins: # optional, default is 
          
